<!-- application/views/scripts/guestbook/index.phtml -->
<div id="view-content">
	<p>
            <a href="<?php echo $this->url(array('controller' => 'guestbook','action' => 'sign'),'default', true); ?>">
                Sign Our Guestbook
            </a>
        </p>
        <p>
            Guestbook Entries:
            <br />
        <dl>
            <?php foreach($this->entries as $entry): ?>
            <dt><?php $this->escape($entry->email); ?></dt>
            <dd><?php $this->escape($entry->comment); ?></dd>
            <?php endforeach; ?>
        </dl>
        </p>
</div>