<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
       <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
       <title>Quickstart Application</title>
       <?php echo $this->headlink()->appendStylesheet('/quickstart/css/styles.css'); ?>
    <body>
        <div id="header"> 
            <div id="headerLogo">SN llc</div>
            <div id="headerNavigation">
                <a href="<?php echo $this->url(array('controller'=>'guestbook'),'default',true) ?>">Guestbook</a>
                <a href="<?php echo $this->url(array('controller'=>'about'), 'default',true); ?>">About Us</a>
            </div>
        </div>
        <div id="contentMain">
            <?php echo $this->layout()->content; ?> 
        </div>
    </body>
</html>